services:
  periphery:
    image: ${KOMODO_INFRA_IMAGE_PREFIX:-}ghcr.io/moghtech/komodo-periphery:2
    init: true
    restart: always
    ports:
      - 8120:8120
    volumes:
      - ${KOMODO_INFRA_DATA_DIR}/komodo-keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${KOMODO_INFRA_DATA_DIR}/komodo-periphery:/etc/komodo
      - /data:/data
      - /root:/root
    environment:
      PERIPHERY_CORE_PUBLIC_KEYS: MCowBQYDK2VuAyEAMnQVnJN2WVoWyyWbaA8R8wzvon/XJ2cYQzvpb7S14TU=
      PERIPHERY_SSL_ENABLED: true
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_LOGGING_PRETTY: false
      PERIPHERY_PRETTY_STARTUP_CONFIG: false
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"

  tailscale:
    image: ${KOMODO_INFRA_IMAGE_PREFIX:-}tailscale/tailscale:latest
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - ${KOMODO_INFRA_DATA_DIR}/tailscale:/var/lib/tailscale
    environment:
      TS_ACCEPT_DNS: false
      TS_USERSPACE: false
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY:-}
      TS_HOSTNAME: ${TAILSCALE_HOSTNAME}
      TS_EXTRA_ARGS: --snat-subnet-routes=false --advertise-tags=${TAILSCALE_TAGS} --advertise-exit-node=false
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale/state
    post_start:
      - command: sh -c 'until tailscale status >/dev/null 2>&1; do sleep 1; done; tailscale set --hostname="${TAILSCALE_HOSTNAME}" --advertise-exit-node=false --advertise-routes= --snat-subnet-routes=false; if [ -n "${TS_RELAY_SERVER_PORT:-}" ]; then tailscale set --relay-server-port="${TS_RELAY_SERVER_PORT:-}"; else tailscale set --relay-server-port=""; fi'

  watchtower:
    image: ${KOMODO_INFRA_IMAGE_PREFIX:-}nickfedor/watchtower:latest
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    command:
      - --label-enable
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
