services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    init: true
    restart: always
    ports:
      - 8120:8120
    volumes:
      - ./komodo-keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ./komodo-periphery:/etc/komodo
      - /data:/data
      - /root:/root
    environment:
      PERIPHERY_CORE_PUBLIC_KEYS: MCowBQYDK2VuAyEAMnQVnJN2WVoWyyWbaA8R8wzvon/XJ2cYQzvpb7S14TU=
      PERIPHERY_SSL_ENABLED: true
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_LOGGING_PRETTY: false
      PERIPHERY_PRETTY_STARTUP_CONFIG: false
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos
    labels:
      komodo.skip:

  tailscale:
    image: tailscale/tailscale:latest
    restart: always
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - ${DATA_PATH}/tailscale:/var/lib/tailscale
    environment:
      TS_ACCEPT_DNS: false
      TS_USERSPACE: false
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_HOSTNAME: ${HOST_NAME}
      TS_EXTRA_ARGS: --advertise-exit-node --snat-subnet-routes=false
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale/state