services:
  easytier:
    image: easytier/easytier:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - stack.env
    environment:
      ET_NETWORK_SECRET: ${ET_NETWORK_SECRET}
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${GAMES_PATH}/easytier:/root

  localtonet:
    image: localtonet/localtonet:latest
    network_mode: host
    restart: unless-stopped
    command: '--authtoken ${LOCALTONET_TOKEN}'

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    network_mode: host
    restart: unless-stopped
    environment:
      SECRET_KEY: ${PLAYIT_TOKEN}
