services:
  mongo:
    image: ${KOMODO_INFRA_DOCKER_IMAGE_PREFIX:-}mongo:latest
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    env_file:
      - .env
    # ports:
    #   - 27017:27017
    volumes:
      - ${KOMODO_INFRA_DATA_DIR}/mongo-data:/data/db
      - ${KOMODO_INFRA_DATA_DIR}/mongo-config:/data/configdb
  
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-2}
    init: true
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - 9120:9120
    volumes:
      ## Attach the Core / Periphery communication keys
      - ${KOMODO_INFRA_DATA_DIR}/keys:/config/keys
      ## Core cache for repos for latest commit hash / contents
      - ${KOMODO_INFRA_DATA_DIR}/repo-cache:/repo-cache
      ## Store sync files on server
      - ${KOMODO_INFRA_DATA_DIR}/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
      - ${KOMODO_INFRA_DATA_DIR}/backups:/backups
    ## Allows for systemd Periphery connection at "http://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-2}
    init: true
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    depends_on:
      - core
    env_file:
      - .env
    volumes:
      - ${KOMODO_INFRA_DATA_DIR}/keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /sys:/sys:ro
      - ${KOMODO_INFRA_DATA_DIR}/periphery:/etc/komodo
      - /data:/data

  watchtower:
    image: ${KOMODO_INFRA_DOCKER_IMAGE_PREFIX:-}nickfedor/watchtower:latest
    labels:
      komodo.skip:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    command:
      - --label-enable
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
