services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    restart: unless-stopped
    labels:
      caddy: code.${COMMON_DOMAIN_A}
      caddy.import: common_tls
      caddy.reverse_proxy: "{{upstreams 3000}}"
    env_file:
      - stack.env
    environment:
      FORGEJO__SERVER__DOMAIN: code.${COMMON_DOMAIN_A}
      FORGEJO__SERVER__ROOT_URL: https://code.${COMMON_DOMAIN_A}
      FORGEJO__SERVER__SSH_DOMAIN: code-ssh.${COMMON_DOMAIN_A}
      FORGEJO__MAILER__FROM: Forgejo <no-reply@${COMMON_DOMAIN_A}>
      FORGEJO__MAILER__SMTP_ADDR: ${EMAIL_SMTP_HOST}
      FORGEJO__MAILER__USER: ${EMAIL_SMTP_USERNAME}
      FORGEJO__MAILER__PASSWD: ${EMAIL_SMTP_PASSWORD}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_USERNAME: ${EMAIL_SMTP_USERNAME}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
    networks:
      - shared_forgejo_net
    #ports:
    #  - '3000:3000'
    #  - '222:22'
    volumes:
      - ${BLOBSTORE_PATH}/forgejo:/data

  renovate:
    image: renovate/renovate:full
    restart: none
    volumes:
      - /tmp/renovate-cache:/tmp/renovate-cache
    env_file:
      - stack.env
    environment:
      RENOVATE_ENDPOINT: https://code.${COMMON_DOMAIN_A}/api/v1/
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
networks:
  shared_forgejo_net:
    external: true
