[[server]]
name = "camtr-ovh-01-sandbox"
[server.config]
address = "https://100.66.120.116:8120"
region = "ca-central"
enabled = true

##

[[server]]
name = "camtr-ovh-01-services"
[server.config]
address = "https://100.86.12.41:8120"
region = "ca-central"
enabled = true

##

[[server]]
name = "cator-oracle-01"
[server.config]
address = "https://100.80.22.102:8120"
region = "ca-central"
enabled = true

##

[[server]]
name = "hq-cat-core"
[server.config]
region = "ca-central"
enabled = true

##

[[server]]
name = "hq-cat-games"
[server.config]
address = "https://100.110.4.6:8120"
region = "ca-central"
enabled = false

##

[[server]]
name = "hq-cat-services"
[server.config]
address = "https://100.126.143.61:8120"
region = "ca-central"
enabled = true

##

[[server]]
name = "hq-cat-sandbox"
[server.config]
address = "https://100.103.135.32:8120"
region = "ca-central"
enabled = true

##

[[server]]
name = "hq-nya-services"
[server.config]
address = "https://100.106.116.9:8120"
region = "cn-north"

##

[[server]]
name = "jptyo-greencloud-01"
[server.config]
address = "https://100.64.226.106:8120"
region = "ap-northeast"
enabled = true

##

[[server]]
name = "uslax-dmit-01"
[server.config]
address = "https://100.113.240.1:8120"
region = "us-west"
enabled = true

##

[[server]]
name = "uslax-dmit-02"
[server.config]
address = "https://100.107.159.16:8120"
region = "us-west"
enabled = true

##
