services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: media.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.@prowlarr.path: /prowlarr /prowlarr/*
      caddy.@radarr.path: /radarr /radarr/*
      caddy.@sonarr.path: /sonarr /sonarr/*
      caddy.0_handle: /oauth2/*
      caddy.0_handle.reverse_proxy: oauth2-proxy:4180
      caddy.1_redir: /prowlarr /prowlarr/ 308
      caddy.2_handle: "@prowlarr"
      caddy.2_handle.0_import: protected_forward_auth
      caddy.2_handle.1_reverse_proxy: prowlarr:9696
      caddy.3_redir: /radarr /radarr/ 308
      caddy.4_handle: "@radarr"
      caddy.4_handle.0_import: protected_forward_auth
      caddy.4_handle.1_reverse_proxy: radarr:7878
      caddy.5_redir: /sonarr /sonarr/ 308
      caddy.6_handle: "@sonarr"
      caddy.6_handle.0_import: protected_forward_auth
      caddy.6_handle.1_reverse_proxy: sonarr:8989
      caddy.7_handle: /*
      caddy.7_handle.reverse_proxy: jellyfin:8096
    volumes:
      - ${APPDATA_PATH}/jellyfin:/config
      - ${MEDIA_PATH}/others:/data/others
      - ${MEDIA_PATH}/decypharr:/mnt/decypharr:ro,rslave
    tmpfs:
      - /cache
    env_file:
      - stack.env

  seerr:
    image: ghcr.io/seerr-team/seerr:preview-new-oidc
    init: true
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: seerr.${COMMON_DOMAIN_A}
      caddy.import: common_tls
      caddy.reverse_proxy: "{{upstreams 5055}}"
    volumes:
      - ${APPDATA_PATH}/seerr:/app/config
    env_file:
      - stack.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  decypharr:
    image: cy01/blackhole:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: decypharr.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.import_1: protected_reverse_proxy "{{upstreams 8282}}"
    volumes:
      - ${APPDATA_PATH}/decypharr:/app
      - ${APPDATA_PATH}/decypharr/fuse.conf:/etc/fuse.conf:ro
      - ${MEDIA_PATH}/decypharr:/mnt/decypharr:rshared
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
      - no-new-privileges=false
    env_file:
      - stack.env
    environment:
      DECYPHARR_DOWNLOAD_FOLDER: /mnt/decypharr/downloads
      DECYPHARR_MOUNT__DFS__CACHE_DIR: /tmp/decypharr-cache
      DECYPHARR_MOUNT__DFS__GID: ${PGID}
      DECYPHARR_MOUNT__DFS__UID: ${PUID}
      DECYPHARR_MOUNT__DFS__UMASK: ${UMASK}

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    env_file:
      - stack.env
    environment:
      PROWLARR__SERVER__URLBASE: /prowlarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${MEDIA_PATH}/decypharr:/mnt/decypharr:rslave
    env_file:
      - stack.env
    environment:
      RADARR__SERVER__URLBASE: /radarr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${MEDIA_PATH}/decypharr:/mnt/decypharr:rslave
    env_file:
      - stack.env
    environment:
      SONARR__SERVER__URLBASE: /sonarr

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    volumes:
      - ${APPDATA_PATH}/flaresolverr:/config
    env_file:
      - stack.env

networks:
  shared_media_net:
    external: true
