services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    tty: true
    networks:
      - shared_ollama_net
    env_file:
      - stack.env
    volumes:
      - ${BLOBSTORE_PATH}/ollama:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '4.0'

networks:
  shared_ollama_net:
    external: true
