services:
  teamspeak:
    image: teamspeak:latest
    restart: unless-stopped
    ports:
      - ${TEAMSPEAK_VOICE_PORT}:9987/udp
      - ${TEAMSPEAK_FILETRANSFER_PORT}:30033/tcp
    env_file:
      - stack.env
    volumes:
      - ${APPDATA_PATH}/teamspeak:/var/ts3server
