services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - ${APPDATA_PATH}/dokploy/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DOKPLOY_POSTGRES_USER} -d ${DOKPLOY_POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dokploy_internal_net

  redis:
    image: redis:8
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ${APPDATA_PATH}/dokploy/redis:/data
    networks:
      - dokploy_internal_net

  dokploy:
    image: creamed/dokpoly:latest-nightly
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      caddy: dokploy.${COMMON_DOMAIN_A}
      caddy.import: common_tls
      caddy.reverse_proxy: "{{upstreams 3000}}"
    env_file:
      - stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_PATH}/dokploy/etc:/etc/dokploy
      - ${APPDATA_PATH}/dokploy/docker:/root/.docker
    networks:
      - shared_dokpoly_net
      - dokploy_internal_net
      - dokploy-network

  traefik:
    image: traefik:v3.6.12
    restart: unless-stopped
    depends_on:
      - dokploy
    command:
      - --providers.file.filename=/etc/traefik/traefik.yml
    volumes:
      - ${APPDATA_PATH}/dokploy/etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dokploy-network

networks:
  shared_dokpoly_net:
    external: true
  dokploy_internal_net:
    internal: true
  dokploy-network:
