[[stack]]
name = "camtr-ovh-01-sandbox-runner"
[stack.config]
server = "camtr-ovh-01-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/camtr-ovh-01-sandbox/runner"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
FORGEJO_DOMAIN=code.[[COMMON_DOMAIN_A]]
FORGEJO_RUNNER_REGISTRATION_TOKEN=[[CAMTROVH01_RUNNER_FORGEJO_REGISTRATION_TOKEN]]
"""

##