[[stack]]
name = "cator-oracle-01-networking"
tags = ["auto-deploy"]
[stack.config]
server = "cator-oracle-01"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/cator-oracle-01/networking"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_dokpoly_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
CLOUDFLARE_API_TOKEN=[[COMMON_CF_API_TOKEN]]
COMMON_CADDY_ADMIN_EMAIL=[[COMMON_CADDY_ADMIN_EMAIL]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
CATOR_ORACLE_01_CFD_TOKEN=[[CATOR_ORACLE_01_CFD_TOKEN]]
"""

##

[[stack]]
name = "cator-oracle-01-dokpoly"
[stack.config]
server = "cator-oracle-01"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/cator-oracle-01/dokpoly"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
DOKPLOY_POSTGRES_PASSWORD=[[CATOR_ORACLE_01_DOKPOLY_POSTGRES_PASSWORD]]
"""

##
