[[stack]]
name = "hq-cat-sandbox-dokpoly"
[stack.config]
server = "hq-cat-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-sandbox/dokpoly"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
HQCAT_SANDBOX_CFD_TOKEN=[[HQCAT_SANDBOX_CFD_TOKEN]]
"""

##