[[stack]]
name = "hq-cat-services-networking"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/networking"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
CLOUDFLARE_API_TOKEN=[[COMMON_CF_API_TOKEN]]
COMMON_CADDY_ADMIN_EMAIL=[[COMMON_CADDY_ADMIN_EMAIL]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
HQCAT_SERVICES_CFD_TOKEN=[[HQCAT_SERVICES_CFD_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-services-ollama"
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/ollama"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_ollama_net || true
"""
extra_args = ["--remove-orphans"]

##

[[stack]]
name = "hq-cat-services-lobechat"
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/lobechat"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_lobechat_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
POSTGRES_PASSWORD=[[HQCAT_SERVICES_LOBE_DBPWD]]
KEY_VAULTS_SECRET=[[HQCAT_SERVICES_LOBE_KEYVAULT_SECRET]]
AUTH_SECRET=[[HQCAT_SERVICES_LOBE_AUTH_SECRET]]
S3_ENDPOINT=[[HQCAT_SERVICES_LOBE_S3_ENDPOINT]]
S3_ACCESS_KEY_ID=[[HQCAT_SERVICES_LOBE_S3_ACCESS_KEY_ID]]
S3_SECRET_ACCESS_KEY=[[HQCAT_SERVICES_LOBE_S3_SECRET_ACCESS_KEY]]
JWKS_KEY=[[HQCAT_SERVICES_LOBE_JWKS_KEY]]
AUTH_GENERIC_OIDC_SECRET=[[HQCAT_SERVICES_LOBE_OIDC_SECRET]]
QSTASH_TOKEN=[[HQCAT_SERVICES_LOBE_QSTASH_TOKEN]]
COHERE_API_KEY=[[HQCAT_SERVICES_LOBE_COHERE_API_KEY]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
"""

##

[[stack]]
name = "hq-cat-services-sure"
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/sure"
additional_env_files = [
  { path = "stack.env", track = true },
  { path = "sure.env", track = true }
]
pre_deploy.command = """
docker network create shared_sure_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
POSTGRES_PASSWORD=[[HQCAT_SERVICES_SURE_DBPWD]]
SMTP_USERNAME=[[COMMON_SMTP_01_SERVER_USERNAME]]
SMTP_PASSWORD=[[COMMON_SMTP_01_SERVER_PASSWORD]]
SMTP_ADDRESS=[[COMMON_SMTP_01_SERVER_ADDRESS]]

SECRET_KEY_BASE=[[HQCAT_SERVICES_SURE_SECRET_KEY_BASE]]
OPENAI_ACCESS_TOKEN=[[HQCAT_SERVICES_SURE_OPENAI_ACCESS_TOKEN]]
BRAND_FETCH_CLIENT_ID=[[HQCAT_SERVICES_SURE_BRANDFETCH_CLIENT_ID]]
# TWELVE_DATA_API_KEY=[[HQCAT_SERVICES_SURE_TWELVE_DATA_API_KEY]]
POSTHOG_KEY=[[HQCAT_SERVICES_SURE_POSTHOG_KEY]]

OIDC_CLIENT_SECRET=[[HQCAT_SERVICES_SURE_OIDC_CLIENT_SECRET]]
"""

##

[[stack]]
name = "hq-cat-services-sub2api"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/sub2api"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_sub2api_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
JWT_SECRET=[[HQCAT_SERVICES_SUB2API_JWT_SECRET]]
TOTP_ENCRYPTION_KEY=[[HQCAT_SERVICES_SUB2API_TOTP_ENCRYPTION_KEY]]
GH_TOKEN=[[HQCAT_SERVICES_SUB2API_GH_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-services-trek"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/trek"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_trek_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
ENCRYPTION_KEY=[[HQCAT_SERVICES_TREK_ENCRYPTION_KEY]]
OIDC_CLIENT_SECRET=[[HQCAT_SERVICES_TREK_OIDC_CLIENT_SECRET]]
"""

##

[[stack]]
name = "hq-cat-services-forgejo"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/forgejo"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_forgejo_net || true
"""
extra_args = ["--remove-orphans"]
ignore_services = ["renovate"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]

EMAIL_SMTP_HOST=[[COMMON_SMTP_01_SERVER_ADDRESS]]
EMAIL_SMTP_USERNAME=[[COMMON_SMTP_01_SERVER_USERNAME]]
EMAIL_SMTP_PASSWORD=[[COMMON_SMTP_01_SERVER_PASSWORD]]

RENOVATE_TOKEN=[[HQCAT_SERVICES_FORGEJO_RENOVATE_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-services-immich"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/immich"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
DB_USERNAME=[[HQCAT_SERVICES_IMMICH_DBUSER]]
DB_PASSWORD=[[HQCAT_SERVICES_IMMICH_DBPWD]]
"""

##

[[stack]]
name = "hq-cat-services-seafile"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/seafile"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
INIT_SS_ADMIN_USER=j6lk5
INIT_SS_ADMIN_PASSWORD=[[HQCAT_SERVICES_SFSS_ADMIN_PASSWORD]]
INIT_SEAFILE_MYSQL_ROOT_PASSWORD=[[HQCAT_SERVICES_SFDB_ROOT_PASSWORD]]
JWT_PRIVATE_KEY=[[HQCAT_SERVICES_SF_JWT_PRIVATE_KEY]]
REDIS_PASSWORD=[[HQCAT_SERVICES_SFREDIS_PASSWORD]]
SEAFILE_MYSQL_DB_PASSWORD=[[HQCAT_SERVICES_SFDB_PASSWORD]]
ONLYOFFICE_JWT_SECRET=[[HQCAT_SERVICES_SFOFFICE_JWT_SECRET]]
"""
##
