[[stack]]
name = "hq-cat-sandbox-networking"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-sandbox/networking"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
CLOUDFLARE_API_TOKEN=[[COMMON_CF_API_TOKEN]]
COMMON_CADDY_ADMIN_EMAIL=[[COMMON_CADDY_ADMIN_EMAIL]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
HQCAT_SANDBOX_CFD_TOKEN=[[HQCAT_SANDBOX_CFD_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-sandbox-goclaw"
[stack.config]
server = "hq-cat-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-sandbox/goclaw"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
GOCLAW_GATEWAY_TOKEN=[[HQCAT_SANDBOX_GOCLAW_GATEWAY_TOKEN]]
GOCLAW_ENCRYPTION_KEY=[[HQCAT_SANDBOX_GOCLAW_ENCRYPTION_KEY]]
"""

##

[[stack]]
name = "hq-cat-sandbox-remnawave-node"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-sandbox/remnawave-node"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
REMNANODE_SECRET_KEY=[[HQCAT_SANDBOX_REMNANODE_SECRET_KEY]]
"""

##

[[stack]]
name = "hq-cat-sandbox-hermes"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-sandbox"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-sandbox/hermes"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_hermes_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
HERMES1_TELEGRAM_BOT_TOKEN=[[HQCAT_SANDBOX_HERMES1_TELEGRAM_BOT_TOKEN]]
HERMES1_TELEGRAM_ALLOWED_USERS=[[HQCAT_SANDBOX_HERMES1_TELEGRAM_ALLOWED_USERS]]
HERMES2_TELEGRAM_BOT_TOKEN=[[HQCAT_SANDBOX_HERMES2_TELEGRAM_BOT_TOKEN]]
HERMES2_TELEGRAM_ALLOWED_USERS=[[HQCAT_SANDBOX_HERMES2_TELEGRAM_ALLOWED_USERS]]
"""

##
