[[stack]]
name = "hq-cat-games-gateway"
tags = ["ingress"]
[stack.config]
server = "hq-cat-games"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-games/gateway"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
ET_NETWORK_SECRET=[[HQCAT_GAMES_ET_NETWORK_SECRET]]
PLAYIT_TOKEN=[[HQCAT_GAMES_PLAYIT_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-games-mc-prominence-2"
[stack.config]
server = "hq-cat-games"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-games/mc-prominence-2"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
RCON_PASSWORD=[[HQCAT_GAMES_MC_ROCNPWD]]
"""

##

[[stack]]
name = "hq-cat-games-mc-craft-to-exile-2"
[stack.config]
server = "hq-cat-games"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-games/mc-craft-to-exile-2"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
RCON_PASSWORD=[[HQCAT_GAMES_CTE2_RCONPWD]]
"""

##

[[stack]]
name = "hq-cat-games-palworld"
[stack.config]
server = "hq-cat-games"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-games/palworld"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
SERVER_PASSWORD=[[HQCAT_GAMES_PAL_SERVER_PASSWORD]]
ADMIN_PASSWORD=[[HQCAT_GAMES_PAL_ADMIN_PASSWORD]]
"""

##
