[[stack]]
name = "hq-cat-services-networking"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/networking"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
CLOUDFLARE_API_TOKEN=[[COMMON_CF_API_TOKEN]]
COMMON_CADDY_ADMIN_EMAIL=[[COMMON_CADDY_ADMIN_EMAIL]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
HQCAT_SERVICES_CFD_TOKEN=[[HQCAT_SERVICES_CFD_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-services-aiapi"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/aiapi"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_aiapi_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
GH_TOKEN=[[HQCAT_SERVICES_AIAPI_GH_TOKEN]]
COPILOT_API_KEY=[[HQCAT_SERVICES_AIAPI_CAAK]]
"""

##

[[stack]]
name = "hq-cat-services-opencode"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/opencode"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_opencode_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
BRAVE_API_KEY=[[HQCAT_SERVICES_BRAVE_API_KEY]]
OPENCODE_SERVER_PASSWORD=[[HQCAT_SERVICES_OPENCODE_SERVER_PASSWORD]]
"""

##

[[stack]]
name = "hq-cat-services-lobechat"
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/lobechat"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_lobechat_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
POSTGRES_PASSWORD=[[HQCAT_SERVICES_LOBE_DBPWD]]
KEY_VAULTS_SECRET=[[HQCAT_SERVICES_LOBE_KEYVAULT_SECRET]]
AUTH_SECRET=[[HQCAT_SERVICES_LOBE_AUTH_SECRET]]
S3_ENDPOINT=[[HQCAT_SERVICES_LOBE_S3_ENDPOINT]]
S3_ACCESS_KEY_ID=[[HQCAT_SERVICES_LOBE_S3_ACCESS_KEY_ID]]
S3_SECRET_ACCESS_KEY=[[HQCAT_SERVICES_LOBE_S3_SECRET_ACCESS_KEY]]
JWKS_KEY=[[HQCAT_SERVICES_LOBE_JWKS_KEY]]
AUTH_GENERIC_OIDC_SECRET=[[HQCAT_SERVICES_LOBE_OIDC_SECRET]]
QSTASH_TOKEN=[[HQCAT_SERVICES_LOBE_QSTASH_TOKEN]]
COHERE_API_KEY=[[HQCAT_SERVICES_LOBE_COHERE_API_KEY]]
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
"""

##

[[stack]]
name = "hq-cat-services-sub2api"
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/sub2api"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_sub2api_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
JWT_SECRET=[[HQCAT_SERVICES_SUB2API_JWT_SECRET]]
TOTP_ENCRYPTION_KEY=[[HQCAT_SERVICES_SUB2API_TOTP_ENCRYPTION_KEY]]
"""

##

[[stack]]
name = "hq-cat-services-forgejo"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/forgejo"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_forgejo_net || true
"""
extra_args = ["--remove-orphans"]
ignore_services = ["renovate"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]

EMAIL_SMTP_HOST=[[COMMON_SMTP_01_SERVER_ADDRESS]]
EMAIL_SMTP_USERNAME=[[COMMON_SMTP_01_SERVER_USERNAME]]
EMAIL_SMTP_PASSWORD=[[COMMON_SMTP_01_SERVER_PASSWORD]]

RENOVATE_TOKEN=[[HQCAT_SERVICES_FORGEJO_RENOVATE_TOKEN]]
"""

##

[[stack]]
name = "hq-cat-services-immich"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/immich"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
DB_USERNAME=[[HQCAT_SERVICES_IMMICH_DBUSER]]
DB_PASSWORD=[[HQCAT_SERVICES_IMMICH_DBPWD]]
"""

##

[[stack]]
name = "hq-cat-services-seafile"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/seafile"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
INIT_SS_ADMIN_USER=j6lk5
INIT_SS_ADMIN_PASSWORD=[[HQCAT_SERVICES_SFSS_ADMIN_PASSWORD]]
INIT_SEAFILE_MYSQL_ROOT_PASSWORD=[[HQCAT_SERVICES_SFDB_ROOT_PASSWORD]]
JWT_PRIVATE_KEY=[[HQCAT_SERVICES_SF_JWT_PRIVATE_KEY]]
REDIS_PASSWORD=[[HQCAT_SERVICES_SFREDIS_PASSWORD]]
SEAFILE_MYSQL_DB_PASSWORD=[[HQCAT_SERVICES_SFDB_PASSWORD]]
ONLYOFFICE_JWT_SECRET=[[HQCAT_SERVICES_SFOFFICE_JWT_SECRET]]
"""

##

[[stack]]
name = "hq-cat-services-remnawave"
tags = ["auto-deploy"]
[stack.config]
server = "hq-cat-services"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/hq-cat-services/remnawave"
additional_env_files = [
  { path = "stack.env", track = true }
]
pre_deploy.command = """
docker network create shared_remnawave_net || true
"""
extra_args = ["--remove-orphans"]
environment = """
COMMON_DOMAIN_A=[[COMMON_DOMAIN_A]]
JWT_AUTH_SECRET=[[HQCAT_SERVICES_REMNAWAVE_JWT_AUTH_SECRET]]
JWT_API_TOKENS_SECRET=[[HQCAT_SERVICES_REMNAWAVE_JWT_API_TOKENS_SECRET]]
METRICS_PASS=[[HQCAT_SERVICES_REMNAWAVE_METRICS_PASS]]
"""
##
