[[stack]]
name = "jptyo-greencloud-01-general"
[stack.config]
server = "jptyo-greencloud-01"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/jptyo-greencloud-01/general"
extra_args = ["--remove-orphans"]
environment = """
APPDATA_PATH=/root/docker
"""
