[[stack]]
name = "uslax-dmit-02-remnawave-node"
tags = ["auto-deploy"]
[stack.config]
server = "uslax-dmit-02"
poll_for_updates = true
auto_update = true
linked_repo = "GitHub-Yggdrasil"
run_directory = "apps/uslax-dmit-02/remnawave-node"
additional_env_files = [
  { path = "stack.env", track = true }
]
extra_args = ["--remove-orphans"]
environment = """
REMNANODE_SECRET_KEY=[[USLAX_DMIT_02_REMNANODE_SECRET_KEY]]
"""
