services:
  hysteria:
    image: tobyxdd/hysteria:latest
    restart: always
    network_mode: host
    volumes:
      - ${APPDATA_PATH}/hysteria/acme:/acme
      - ${APPDATA_PATH}/hysteria/hysteria.yaml:/etc/hysteria.yaml
    command: ["server", "-c", "/etc/hysteria.yaml"]

networks:
  default:
    enable_ipv6: true
