[[alerter]]
name = "Komodo Ntfy"
[alerter.config]
enabled = true
endpoint.type = "Ntfy"
endpoint.params.url = "https://ntfy.sh/komodo-1sz71kbzb9klqj2j"
alert_types = [
  "ServerUnreachable",
  "ServerDisk",
  "AwsBuilderTerminationFailed",
  "BuildFailed",
  "RepoBuildFailed"
]

##
