services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    networks:
      - shared_media_net
    labels:
      caddy: jellyfin.${COMMON_DOMAIN_A}
      caddy.import: common_tls
      caddy.reverse_proxy: "{{upstreams 8096}}"
    # ports:
    #   - 127.0.0.1:8096:8096
    volumes:
      - ${APPDATA_PATH}/jellyfin:/config
      - ${MEDIA_PATH}/tvshows:/data/tvshows
      - ${MEDIA_PATH}/others:/data/others
      - ${MEDIA_PATH}/movies:/data/movies
      - ${MEDIA_PATH}/musics:/data/musics
    tmpfs:
      - /cache
    restart: unless-stopped
    env_file:
      - stack.env

  gluetun:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - shared_media_net
    labels:
      caddy: qbt.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.1_handle: /oauth2/*
      caddy.1_handle.reverse_proxy: oauth2-proxy-qbt:4180
      caddy.2_handle: /*
      caddy.2_handle.forward_auth: http://oauth2-proxy-qbt:4180
      caddy.2_handle.forward_auth.1_uri: /oauth2/auth
      caddy.2_handle.forward_auth.2_@error: status 401
      caddy.2_handle.forward_auth.3_handle_response: "@error"
      caddy.2_handle.forward_auth.3_handle_response.1_redir: "* /oauth2/sign_in?rd={scheme}://{host}{uri} 302"
      caddy.2_handle.reverse_proxy: "{{upstreams 8080}}"
      caddy.2_handle.reverse_proxy.header_up_0: -Referer
    #ports:
    #  - 8080:8080
    volumes:
      - ${APPDATA_PATH}/gluetun:/gluetun
      - /tmp-gluetun:/tmp/gluetun
    env_file:
      - stack.env
    environment:
      VPN_SERVICE_PROVIDER: private internet access
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      SERVER_REGIONS: CA Montreal
      VPN_PORT_FORWARDING: true

  oauth2-proxy-qbt-redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --save 60 1000 --appendonly yes
    volumes:
      - ${APPDATA_PATH}/oauth2-proxy-qbt-redis:/data
    networks:
      - oauth2-proxy-qbt-intranet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  oauth2-proxy-qbt:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    networks:
      - shared_media_net
      - oauth2-proxy-qbt-intranet
    env_file:
      - stack.env
    environment:
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_CLIENT_ID: 6b6d7d3f-3b3c-47be-a213-f3735bda6c73
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_COOKIE_NAME: __Secure-qbt-oauth2-proxy
      OAUTH2_PROXY_COOKIE_SECURE: true
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_COOKIE_EXPIRE: 24h
      OAUTH2_PROXY_COOKIE_REFRESH: 1h
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: 5m
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://oauth2-proxy-qbt-redis:6379
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://id.${COMMON_DOMAIN_A}
      OAUTH2_PROXY_REDIRECT_URL: https://qbt.${COMMON_DOMAIN_A}/oauth2/callback
      OAUTH2_PROXY_WHITELIST_DOMAINS: qbt.${COMMON_DOMAIN_A}
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_TRUSTED_PROXY_IPS: 172.16.0.0/12
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
    depends_on:
      oauth2-proxy-qbt-redis:
        condition: service_healthy
  
  gluetun-qbittorrent-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:latest
    restart: unless-stopped
    volumes:
      - /tmp-gluetun:/tmp/gluetun
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent
    env_file:
      - stack.env
    environment:
      QBITTORRENT_SERVER: localhost
      QBITTORRENT_PORT: 8080
      PORT_FORWARDED: /tmp/gluetun/forwarded_port
      HTTP_S: http
  
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 127.0.0.1:8080:8080
    volumes:
      - ${APPDATA_PATH}/qbittorrent:/config
      - ${DOWNLOADS_PATH}/qbittorrent:/downloads
    env_file:
      - stack.env

  peerbanhelper:
    image: ghostchu/peerbanhelper:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: pbh.${COMMON_DOMAIN_A}
      caddy.import: common_tls
      caddy.reverse_proxy: "{{upstreams 9898}}"
    volumes:
      - ${APPDATA_PATH}/peerbanhelper:/app/data
      - /tmp/peerbanhelper:/tmp
    # ports:
    #   - 9898:9898
    env_file:
      - stack.env

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: prowlarr.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.1_forward_auth: https://sso.${COMMON_DOMAIN_A}
      caddy.1_forward_auth.1_uri: /oauth2/auth
      caddy.1_forward_auth.2_@error: status 401
      caddy.1_forward_auth.3_handle_response: "@error"
      caddy.1_forward_auth.3_handle_response.1_redir: "* https://sso.${COMMON_DOMAIN_A}/oauth2/sign_in?rd={scheme}://{host}{uri} 302"
      caddy.reverse_proxy: "{{upstreams 9696}}"
    # ports:
    #   - 9696:9696
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    env_file:
      - stack.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: radarr.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.1_@protected: not path /api/* /ping
      caddy.2_forward_auth: "@protected https://sso.${COMMON_DOMAIN_A}"
      caddy.2_forward_auth.1_uri: /oauth2/auth
      caddy.2_forward_auth.2_@error: status 401
      caddy.2_forward_auth.3_handle_response: "@error"
      caddy.2_forward_auth.3_handle_response.1_redir: "* https://sso.${COMMON_DOMAIN_A}/oauth2/sign_in?rd={scheme}://{host}{uri} 302"
      caddy.reverse_proxy: "{{upstreams 7878}}"
    # ports:
    #   - 7878:7878
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${DOWNLOADS_PATH}/qbittorrent:/downloads
    env_file:
      - stack.env

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - shared_media_net
    labels:
      caddy: sonarr.${COMMON_DOMAIN_A}
      caddy.import_0: common_tls
      caddy.1_@protected: not path /api/* /ping
      caddy.2_forward_auth: "@protected https://sso.${COMMON_DOMAIN_A}"
      caddy.2_forward_auth.1_uri: /oauth2/auth
      caddy.2_forward_auth.2_@error: status 401
      caddy.2_forward_auth.3_handle_response: "@error"
      caddy.2_forward_auth.3_handle_response.1_redir: "* https://sso.${COMMON_DOMAIN_A}/oauth2/sign_in?rd={scheme}://{host}{uri} 302"
      caddy.reverse_proxy: "{{upstreams 8989}}"
    # ports:
    #   - 8989:8989
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${MEDIA_PATH}/tvshows:/tvshows
      - ${DOWNLOADS_PATH}/qbittorrent:/downloads
    env_file:
      - stack.env

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    networks:
      shared_media_net:
    # ports:
    #   - 8191:8191
    volumes:
      - ${APPDATA_PATH}/flaresolverr:/config
    env_file:
      - stack.env

networks:
  shared_media_net:
    external: true
  oauth2-proxy-qbt-intranet:
    internal: true
